version: '3.1'
services:
  stats-server:
    build: ./stats
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
    networks:
      - stats-server
      - services

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6543:5432"
    environment:
      POSTGRES_DB: "stats"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_PORT: 5433
    networks:
      - stats-server

  ewm-service:
    build: ./main
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
    networks:
      - ewm-service
      - services

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: "ewm"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      DB_HOST: "ewm-db"
      DB_PORT: 5432
    networks:
      - ewm-service

networks:
  ewm-service:
    driver: bridge
  stats-server:
    driver: bridge
  services:
    driver: bridge