create table if not exists stats_hit
(
    id        bigint generated by default as identity
        primary key,
    app       varchar(255),
    ip        varchar(255),
    timestamp timestamp,
    uri       varchar(255)
);